[2024-06-30T08:38:27.674+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T08:38:27.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [queued]>
[2024-06-30T08:38:27.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [queued]>
[2024-06-30T08:38:27.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-30T08:38:27.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 08:38:24.128669+00:00
[2024-06-30T08:38:27.726+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T08:38:27.727+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-06-30T08:38:27.728+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T08:38:24.128669+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmpb7o6q5v2']
[2024-06-30T08:38:27.730+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask data_delivery
[2024-06-30T08:38:27.741+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T08:38:27.770+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T08:38:27.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T08:38:24.128669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T08:38:24.128669+00:00'
[2024-06-30T08:38:27.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T08:38:27.880+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T08:38:27.881+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T08:38:27.881+0000] {Transform_data.py:51} INFO - start Extracting dim employee
[2024-06-30T08:38:27.885+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.889+0000] {Transform_data.py:60} INFO - Extract dim employees done
[2024-06-30T08:38:27.889+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.893+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.895+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T08:38:27.903+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.904+0000] {Load_data.py:158} INFO - Loading dimproduct to db...
[2024-06-30T08:38:27.904+0000] {Transform_data.py:27} INFO - Start Extracting dim product
[2024-06-30T08:38:27.907+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.909+0000] {Transform_data.py:41} INFO - Extract dim products done
[2024-06-30T08:38:27.910+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.912+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.916+0000] {Load_data.py:170} INFO - SCD type 1 on dimproduct started
[2024-06-30T08:38:27.932+0000] {Load_data.py:209} ERROR - Error while loading dimProducts: "Only a column name can be used for the key in a dtype mappings argument. 'Product_id' not found in columns."
[2024-06-30T08:38:27.933+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T08:38:27.933+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T08:38:27.936+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.939+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T08:38:27.939+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.943+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.945+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T08:38:27.960+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.960+0000] {Load_data.py:214} INFO - Loading factsales to db ...
[2024-06-30T08:38:27.960+0000] {Transform_data.py:70} INFO - start Extracting fact sales
[2024-06-30T08:38:27.963+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.967+0000] {Transform_data.py:81} INFO - Extract fact sales done
[2024-06-30T08:38:27.967+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.971+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T08:38:27.974+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:38:27.991+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table fact_sales With 58 Row
[2024-06-30T08:38:27.992+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:38:27.992+0000] {Load_data.py:222} INFO - Fact_Sales loaded successfully
[2024-06-30T08:38:27.992+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T08:38:27.992+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T08:38:27.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T08:38:28.001+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T08:38:24.128669+00:00, execution_date=20240630T083824, start_date=20240630T083827, end_date=20240630T083828
[2024-06-30T08:38:28.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T08:38:28.037+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T08:38:28.039+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
