[2024-06-30T09:14:26.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T09:14:26.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T09:14:23.505682+00:00 [queued]>
[2024-06-30T09:14:26.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T09:14:23.505682+00:00 [queued]>
[2024-06-30T09:14:26.997+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-30T09:14:27.008+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 09:14:23.505682+00:00
[2024-06-30T09:14:27.016+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T09:14:27.017+0000] {standard_task_runner.py:63} INFO - Started process 182 to run task
[2024-06-30T09:14:27.018+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T09:14:23.505682+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmpka7hnb_6']
[2024-06-30T09:14:27.019+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask data_delivery
[2024-06-30T09:14:27.030+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T09:14:27.058+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T09:14:23.505682+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T09:14:27.144+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T09:14:23.505682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T09:14:23.505682+00:00'
[2024-06-30T09:14:27.145+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T09:14:27.159+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T09:14:27.160+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T09:14:27.160+0000] {Transform_data.py:51} INFO - start Extracting dim employee
[2024-06-30T09:14:27.163+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.167+0000] {Transform_data.py:60} INFO - Extract dim employees done
[2024-06-30T09:14:27.167+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.172+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.174+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T09:14:27.181+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.181+0000] {Load_data.py:159} INFO - Loading dimproduct to db...
[2024-06-30T09:14:27.181+0000] {Transform_data.py:27} INFO - Start Extracting dim product
[2024-06-30T09:14:27.185+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.187+0000] {Transform_data.py:41} INFO - Extract dim products done
[2024-06-30T09:14:27.187+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.191+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.193+0000] {Load_data.py:172} INFO - SCD type 1 on dimproduct started
[2024-06-30T09:14:27.208+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: integer out of range

[2024-06-30T09:14:27.210+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.213+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.215+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.216+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.218+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.219+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.220+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.222+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.223+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.225+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.226+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.228+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.230+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.232+0000] {db_utils.py:40} INFO - Error while executing query for table dim_products: current transaction is aborted, commands ignored until end of transaction block

[2024-06-30T09:14:27.232+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.233+0000] {Load_data.py:232} INFO - Loading dim_products completed successfully
[2024-06-30T09:14:27.233+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T09:14:27.233+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T09:14:27.236+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.239+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T09:14:27.239+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.243+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.246+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T09:14:27.261+0000] {db_utils.py:37} INFO - Query executed successfully for table dim_customers
[2024-06-30T09:14:27.265+0000] {Tables_creations.py:27} INFO - Loading data into table dim_customers...
[2024-06-30T09:14:27.268+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.270+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table dim_customers With 1 Row
[2024-06-30T09:14:27.271+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.271+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.271+0000] {Load_data.py:238} INFO - Loading factsales to db ...
[2024-06-30T09:14:27.271+0000] {Transform_data.py:70} INFO - start Extracting fact sales
[2024-06-30T09:14:27.274+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.277+0000] {Transform_data.py:81} INFO - Extract fact sales done
[2024-06-30T09:14:27.278+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.281+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T09:14:27.285+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T09:14:27.300+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table fact_sales With 58 Row
[2024-06-30T09:14:27.300+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T09:14:27.301+0000] {Load_data.py:246} INFO - Fact_Sales loaded successfully
[2024-06-30T09:14:27.301+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T09:14:27.301+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T09:14:27.302+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T09:14:27.309+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T09:14:23.505682+00:00, execution_date=20240630T091423, start_date=20240630T091426, end_date=20240630T091427
[2024-06-30T09:14:27.351+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T09:14:27.366+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T09:14:27.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
